<a href="https://colab.research.google.com/github/aliciawill/BigData/blob/master/(3_3)%EC%9E%84%EC%A0%95%EC%9B%90_(%EB%8D%B0%EC%82%AC_%EC%99%84%EC%A3%BC%EB%B0%98)_4%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## [4주차] PCA를 통해 신체 지수 만들기

- sklearn의 Linnerrud 데이터셋은 피트니스 클럽의 20대 중반 남성 20명에 대해 
턱걸이, 윗몸일으키기, 점프 / 체중, 허리둘레, 맥박을 측정한 자료입니다.
  - ##### 요구사항1) Linnerrud 데이터셋의 상세 설명을 print 하세요
    - ##### *힌트1) .DESCR을 통해 데이터셋에 대한 설명을 알 수 있다.*
  
  - ##### 요구사항2) data와 target 매서드의 데이터를 모두 병합해 total이란 변수에 저장해주세요. [Chins, Situps, Jumps, Weight, Waist and Pulse] 순
    - ##### *힌트2) np.stack (vstack과 hstack 중 알맞은 것을 선택)

  - ##### 요구사항3) total 데이터를 1개의 차원으로 축소해 하나의 신체 지수를 body_index에 저장해주세요.

  - ##### 요구사항4) body_index를 다시 복원한 data를 recovered_data에 저장하고 total과 recovered_data를 각각 출력하세요

 - ##### 요구사항5) pca 변환을 통해 total의 분산을 몇% 나타내는지 explained_variance 변수에 저장하고 이를 소수 둘째 자리에서 반올림해 출력하세요.
  - * 힌트4) pca.explained_variance_ratio*
  - * 힌트5) type에러가 왜 발생하고, 어떻게 해결할 수 있을지 고민해보세요.



  - ##### 요구사항1) Linnerrud 데이터셋의 상세 설명을 print 하세요
    - ##### *힌트1) .DESCR을 통해 데이터셋에 대한 설명을 알 수 있다.*

In [ ]:
# 여기에 코드를 작성해주세요.

from sklearn.datasets import load_linnerud
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd

ll = load_linnerud()



### ------------ 위는 수정하지 마세요---------- ###
# 문제의 조건에 맞게 아래 빈 코드를 완성해주세요 #

# 요구사항1.
print(ll.DESCR)

.. _linnerrud_dataset:

Linnerrud dataset
-----------------

**Data Set Characteristics:**

    :Number of Instances: 20
    :Number of Attributes: 3
    :Missing Attribute Values: None

The Linnerud dataset constains two small dataset:

- *physiological* - CSV containing 20 observations on 3 exercise variables:
   Weight, Waist and Pulse.

- *exercise* - CSV containing 20 observations on 3 physiological variables:
   Chins, Situps and Jumps.

.. topic:: References

  * Tenenhaus, M. (1998). La regression PLS: theorie et pratique. Paris: Editions Technic.



  - ##### 요구사항2) data와 target 매서드의 데이터를 모두 병합해 total이란 변수에 저장해주세요. [Chins, Situps, Jumps, Weight, Waist and Pulse] 순
    - ##### *힌트2) np.stack (vstack과 hstack 중 알맞은 것을 선택)

In [ ]:
# 요구사항2
total = np.hstack((ll['data'], ll['target'])) 

print(total)

[[  5. 162.  60. 191.  36.  50.]
 [  2. 110.  60. 189.  37.  52.]
 [ 12. 101. 101. 193.  38.  58.]
 [ 12. 105.  37. 162.  35.  62.]
 [ 13. 155.  58. 189.  35.  46.]
 [  4. 101.  42. 182.  36.  56.]
 [  8. 101.  38. 211.  38.  56.]
 [  6. 125.  40. 167.  34.  60.]
 [ 15. 200.  40. 176.  31.  74.]
 [ 17. 251. 250. 154.  33.  56.]
 [ 17. 120.  38. 169.  34.  50.]
 [ 13. 210. 115. 166.  33.  52.]
 [ 14. 215. 105. 154.  34.  64.]
 [  1.  50.  50. 247.  46.  50.]
 [  6.  70.  31. 193.  36.  46.]
 [ 12. 210. 120. 202.  37.  62.]
 [  4.  60.  25. 176.  37.  54.]
 [ 11. 230.  80. 157.  32.  52.]
 [ 15. 225.  73. 156.  33.  54.]
 [  2. 110.  43. 138.  33.  68.]]


  - ##### 요구사항3) total 데이터를 1개의 차원으로 축소해 하나의 신체 지수를 body_index에 저장해주세요.

In [ ]:
pca1 = PCA(n_components=1)
X_low = pca1.fit_transform(total)
X2 = pca1.inverse_transform(X_low)
print(X_low)
print(X2)

[[  4.84819239]
 [-36.37337868]
 [-19.71530279]
 [-48.87880057]
 [ -1.24439301]
 [-52.7513643 ]
 [-59.41274725]
 [-32.28039126]
 [ 26.78843143]
 [192.82401404]
 [-37.38376798]
 [ 79.442903  ]
 [ 79.6880306 ]
 [-99.21237644]
 [-85.61627864]
 [ 76.83255115]
 [-94.42592828]
 [ 76.29783425]
 [ 68.59828074]
 [-38.02550839]]
[[  9.68240123 149.40974964  73.12363867 177.85161938  35.28616082
   56.1855779 ]
 [  7.70641862 116.59237538  49.11575846 184.21469709  36.2540741
   55.45795509]
 [  8.50493424 129.85422583  58.81759854 181.64330962  35.86293004
   55.75199522]
 [  7.10696316 106.63654159  41.83246811 186.1450692   36.54771075
   55.23721556]
 [  9.39034922 144.55931212  69.57525231 178.79208801  35.42921928
   56.07803459]
 [  6.92132931 103.55351078  39.57704592 186.74284904  36.63864144
   55.16885898]
 [  6.60201163  98.25024137  35.69738584 187.77111885  36.79505568
   55.05127554]
 [  7.90261862 119.8508902   51.49955775 183.58289203  36.1579677
   55.53020248]
 [ 10.73412075 16

In [ ]:
import pandas as pd
df = pd.DataFrame(X2)
print(df)

            0           1           2           3          4          5
0    9.682401  149.409750   73.123639  177.851619  35.286161  56.185578
1    7.706419  116.592375   49.115758  184.214697  36.254074  55.457955
2    8.504934  129.854226   58.817599  181.643310  35.862930  55.751995
3    7.106963  106.636542   41.832468  186.145069  36.547711  55.237216
4    9.390349  144.559312   69.575252  178.792088  35.429219  56.078035
5    6.921329  103.553511   39.577046  186.742849  36.638641  55.168859
6    6.602012   98.250241   35.697386  187.771119  36.795056  55.051276
7    7.902619  119.850890   51.499558  183.582892  36.157968  55.530202
8   10.734121  166.876843   85.901867  174.464862  34.770988  56.572856
9   18.693144  299.061321  182.602751  148.835143  30.872348  59.503634
10   7.657985  115.787983   48.527297  184.370664  36.277799  55.440120
11  13.258147  208.796194  116.568389  166.336970  33.534621  57.502287
12  13.269897  208.991345  116.711154  166.299131  33.528866  57

In [ ]:
body_index = df.index
print(body_index)

RangeIndex(start=0, stop=20, step=1)


In [ ]:
#요구사항3.
body_index = df[0]
print(body_index)

SyntaxError: ignored

  - ##### 요구사항4) body_index를 다시 복원한 data를 recovered_data에 저장하고 total과 recovered_data를 각각 출력하세요

In [ ]:
#요구사항4

recovered_data = 
print(total)
print(recovered_data)

SyntaxError: ignored

 - ##### 요구사항5) pca 변환을 통해 total의 분산을 몇% 나타내는지 explained_variance 변수에 저장하고 이를 소수 둘째 자리에서 반올림해 출력하세요.
  - * 힌트4) pca.explained_variance_ratio*
  - * 힌트5) type에러가 왜 발생하고, 어떻게 해결할 수 있을지 고민해보세요.


In [ ]:
explained_variance = 
print()

SyntaxError: ignored