<a href="https://colab.research.google.com/github/aliciawill/BigData/blob/master/colab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('welcome')

welcome


In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/drive/MyDrive/csv-data/data/ch11_potato.csv')

In [6]:
df

무게
0   122.02
1   131.73
2   130.60
3   131.82
4   132.05
5   126.12
6   124.43
7   132.89
8   122.79
9   129.95
10  126.14
11  134.45
12  127.64
13  125.68

In [7]:
import numpy as np

In [8]:
df2 = pd.DataFrame({
                    "name" : ["hong", "park"], 
                    "age" : [10, 20]
                    })

In [10]:
df2

name  age
0  hong   10
1  park   20

In [11]:
df2.index

RangeIndex(start=0, stop=2, step=1)

In [12]:
df2.values

array([['hong', 10],
       ['park', 20]], dtype=object)

In [13]:
df2.name

0    hong
1    park
Name: name, dtype: object

In [14]:
df2['name']

0    hong
1    park
Name: name, dtype: object

In [15]:
df2.name.index

RangeIndex(start=0, stop=2, step=1)

In [16]:
df2.name.values

array(['hong', 'park'], dtype=object)

In [17]:
df2.name.values.tolist()

['hong', 'park']

In [18]:
df3 = pd.DataFrame(data = [['hong', 10], ['park', 20]],  columns=['name', 'age'])

In [19]:
df3

name  age
0  hong   10
1  park   20

In [20]:
df3.dtypes

name    object
age      int64
dtype: object

In [28]:
#df3['age'] = df3['age'].astype(float)
df3['age'] = df3['age'].astype(int)

In [29]:
df3

name  age
0  hong   10
1  park   20

In [30]:
df3.dtypes

name    object
age      int64
dtype: object

In [31]:
df3.describe()

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [33]:
type(df3['name'])

pandas.core.series.Series

In [34]:
df3['name']

0    hong
1    park
Name: name, dtype: object

In [36]:
df3['name'].index

RangeIndex(start=0, stop=2, step=1)

In [37]:
df3['name'].values

array(['hong', 'park'], dtype=object)

In [38]:
type(df3['name'].values)

numpy.ndarray

In [39]:
mask2 = np.zeros((3,4))
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
arr3 = np.array([
    [7,8,9],
    [10,11,12]
], dtype=np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [43]:
arr2 + arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [44]:
arr2 * arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])