<a href="https://colab.research.google.com/github/aliciawill/BigData/blob/master/vectorize_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [12]:
corpus = ["you know I want your love",
          "l like you",
          "what should I do",
          "I hate you",
          "smile face"
          ]

In [95]:
cv = CountVectorizer()

In [ ]:
# 1. 사전을 만들어라.!! => fit()
# 2. 사전에 들어있는 id로 인코딩을 해라.!! => tranform()
# 3. 1, 2을 함께 처리하고자 하는 경우는 => fit_transform()

In [13]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [14]:
cv.vocabulary_ #사전에 무엇이 들어있는지 확인

{'do': 0,
 'face': 1,
 'hate': 2,
 'know': 3,
 'like': 4,
 'love': 5,
 'should': 6,
 'smile': 7,
 'want': 8,
 'what': 9,
 'you': 10,
 'your': 11}

In [5]:
tfidf = TfidfVectorizer()

In [ ]:
# fit-->transform

In [15]:
tfidf.fit(corpus)

TfidfVectorizer()

In [17]:
tfidf.transform(corpus)

<5x12 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [18]:
tfidf.transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.47412465, 0.        ,
        0.47412465, 0.        , 0.        , 0.47412465, 0.        ,
        0.3175268 , 0.47412465],
       [0.        , 0.        , 0.        , 0.        , 0.83088075,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.55645052, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027, 0.        , 0.        , 0.57735027,
        0.        , 0.        ],
       [0.        , 0.        , 0.83088075, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.55645052, 0.        ],
       [0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 0.        ]])

In [19]:
sentence = ["i like like like hate smile"]

In [22]:
nd2array = cv.transform(sentence).toarray()
nd2array 

array([[0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 0, 0]])

In [23]:
nd2array[0]

array([0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 0, 0])

In [24]:
nd2array2 = tfidf.transform(sentence).toarray()
nd2array2 

array([[0.        , 0.        , 0.30151134, 0.        , 0.90453403,
        0.        , 0.        , 0.30151134, 0.        , 0.        ,
        0.        , 0.        ]])

In [25]:
cv.inverse_transform(nd2array)

[array(['hate', 'like', 'smile'], dtype='<U6')]

In [26]:
tfidf.inverse_transform(nd2array2)

[array(['hate', 'like', 'smile'], dtype='<U6')]

In [29]:
feature_list = cv.get_feature_names() #사전에 무엇이 들어있는지 확인
feature_list

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['do',
 'face',
 'hate',
 'know',
 'like',
 'love',
 'should',
 'smile',
 'want',
 'what',
 'you',
 'your']

In [30]:
# dic <--- list
dictionary = dict()

In [32]:
for index, element in enumerate(feature_list):
  dictionary[index] = element
dictionary

{0: 'do',
 1: 'face',
 2: 'hate',
 3: 'know',
 4: 'like',
 5: 'love',
 6: 'should',
 7: 'smile',
 8: 'want',
 9: 'what',
 10: 'you',
 11: 'your'}

In [33]:
## 스팸을 나타내는 사전을 만들어주세요.(10개)
## 스팸이 아닌 사전을 만들어주세요.(10개)

In [96]:
spam_dict = ["advertise", "promotion", "sales", "hu", "special", "sale","member", "company"]
ham_dict = ["order", "confirm", "check", "customer", "payment", "send", "general", "club"]

In [97]:
cv.fit(spam_dict)

CountVectorizer()

In [98]:
cv.vocabulary_

{'advertise': 0,
 'company': 1,
 'hu': 2,
 'member': 3,
 'promotion': 4,
 'sale': 5,
 'sales': 6,
 'special': 7}

In [67]:
## 광고!! 짱 좋은 판매 홍보전략입니다.!! => 스팸입니다.!!

In [99]:
email = [" promotion !! hu good sales sale check payment"]

In [100]:
result1 = cv.transform(email).toarray()
result1

array([[0, 0, 1, 0, 1, 1, 1, 0]])

In [102]:
cv.fit(ham_dict)

CountVectorizer()

In [103]:
cv.vocabulary_

{'check': 0,
 'club': 1,
 'confirm': 2,
 'customer': 3,
 'general': 4,
 'order': 5,
 'payment': 6,
 'send': 7}

In [104]:
result2 = cv.transform(email).toarray()
result2

array([[1, 0, 0, 0, 0, 0, 1, 0]])

In [83]:
## result1의 0이 아닌 갯수의 합, result2의 0이 아닌 갯수의 합
result1_count = 0
result2_count = 0

In [90]:
type(result1)

numpy.ndarray

In [101]:
for item in result1[0]:
  # print(item > 0)
  if (item != 0):
    result1_count = result1_count + 1
result1_count

6

In [105]:
for item in result2[0]:
  # print(item > 0)
  if (item != 0):
    result2_count = result2_count + 1
result2_count

4

In [106]:
spam_dict2 = ["광고", "홍보", "판매", "허경영", "특가", "세일","회원", "회사"]
ham_dict2 = ["주문", "확인", "체크", "고객", "지불", "배송", "일반", "동호회"]

In [114]:
cv2 = CountVectorizer()

In [115]:
cv2.fit(spam_dict2)

CountVectorizer()

In [116]:
email2 = [" 광고 !! 허경영 good 세일 확인 지불"]

In [117]:
result3 = cv2.transform(email2).toarray()
result3

array([[1, 1, 0, 0, 1, 0, 0, 0]])

In [118]:
cv2.fit(ham_dict2)

CountVectorizer()

In [119]:
result4 = cv2.transform(email2).toarray()
result4

array([[0, 0, 0, 0, 0, 1, 0, 1]])

In [120]:
result3_count = 0
result4_count = 0

In [121]:
for item in result3[0]:
  # print(item > 0)
  if (item != 0):
    result3_count = result3_count + 1
result3_count

for item in result4[0]:
  # print(item > 0)
  if (item != 0):
    result4_count = result4_count + 1
print(result3_count, result4_count)

3 2


In [127]:
[i for i in result4[0] if i != 0]

[1, 1]

In [128]:
sum([i for i in result4[0] if i != 0])

2

In [125]:
[i for i in result3[0] if i != 0]

[1, 1, 1]

In [ ]:
## 감정분류기
# 긍정/부정 사전을 만들어보세요.
# input()이용해서, 문장을 받으면, 긍정인지 부정인지 판단해보세요.
# if-idf vectorizer를 사용해주세요.